a=int(input("Enter 1st Number"))
b=int(input("Enter 2nd Number"))
print("the sum of 2 numbers is equal to",a+b)
print("the difference of 2 numbers is equal to",a-b)
print("the product of these numbers is equal to",a*b)
print("the quotient of these numbers is equal to",a/b)
